# Generated by Django 4.2.1 on 2023-10-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product_name', models.CharField(max_length=30)),
                ('brand_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('quality', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product_name', models.CharField(max_length=30)),
                ('brand_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('quality', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('food_name', models.CharField(max_length=30)),
                ('countryfood', models.CharField(max_length=30)),
                ('quantityfood', models.CharField(max_length=30)),
                ('pricefood', models.IntegerField()),
                ('descriptionfood', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='shopkeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopowner_name', models.CharField(max_length=30)),
                ('shop_name', models.CharField(max_length=30)),
                ('contactnumber', models.IntegerField()),
                ('mailadress', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('confirm_password', models.CharField(max_length=30)),
            ],
        ),
    ]
