# Generated by Django 4.2.1 on 2023-10-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0002_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='confirm_password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='shopowner_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
