# Generated by Django 4.2.1 on 2023-10-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0003_alter_shopkeeper_confirm_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='playzone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('gamename', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('descriptionfood', models.CharField(max_length=100)),
            ],
        ),
    ]
