# Generated by Django 4.2.1 on 2023-10-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0004_playzone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playzone',
            name='descriptionfood',
        ),
        migrations.AddField(
            model_name='playzone',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playzone',
            name='duration',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='playzone',
            name='gamename',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='playzone',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
