# Generated by Django 4.2.1 on 2023-10-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0005_remove_playzone_descriptionfood_playzone_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('filmname', models.CharField(max_length=30)),
                ('show', models.CharField(max_length=30)),
                ('showandendtime', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('review', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
