# Generated by Django 4.2.1 on 2023-10-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0006_theater'),
    ]

    operations = [
        migrations.CreateModel(
            name='parlour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product_name', models.CharField(max_length=30)),
                ('brand_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('quality', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
