# Generated by Django 4.2.5 on 2023-10-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0007_parlour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='name',
        ),
    ]
