# Generated by Django 4.2.5 on 2023-10-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0008_remove_feed_email_remove_feed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
