# Generated by Django 4.1.5 on 2023-12-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qr_app", "0009_alter_feed_message"),
    ]

    operations = [
        migrations.DeleteModel(name="electronic",),
        migrations.DeleteModel(name="fashion",),
        migrations.DeleteModel(name="food",),
        migrations.DeleteModel(name="parlour",),
        migrations.DeleteModel(name="playzone",),
        migrations.DeleteModel(name="theater",),
    ]
