# Generated by Django 4.1.5 on 2023-12-03 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qr_app", "0010_delete_electronic_delete_fashion_delete_food_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("product_name", models.CharField(max_length=30)),
                ("brand_name", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=30)),
                ("quality", models.CharField(max_length=30)),
                ("material", models.CharField(max_length=30)),
                ("color", models.CharField(max_length=30)),
                ("price", models.IntegerField()),
                ("description", models.CharField(max_length=100)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="qr_app.type"
                    ),
                ),
            ],
        ),
    ]
