# Generated by Django 4.1.5 on 2023-12-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qr_app", "0011_type_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
