# Generated by Django 4.1.5 on 2023-12-03 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qr_app", "0012_alter_products_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products", old_name="author", new_name="product_type",
        ),
        migrations.AddField(
            model_name="products",
            name="shopkeeper",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="qr_app.shopkeeper",
            ),
            preserve_default=False,
        ),
    ]
