# Generated by Django 4.1.5 on 2023-12-05 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qr_app", "0013_rename_author_products_product_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shopkeeper", old_name="contactnumber", new_name="floor",
        ),
    ]
